server:
  port: 8080

spring:
  application:
    name: mrb-gateway
  config:
    import: "optional:nacos:application.yml"
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: 572b010e-ff99-4a28-bee4-13260db37c32
        import-check:
          enabled: false
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: 572b010e-ff99-4a28-bee4-13260db37c32
    gateway:
      routes:
        - id: user-service
          uri: lb://mrb-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://mrb-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: meeting-service
          uri: lb://mrb-meeting
          predicates:
            - Path=/api/meeting/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
